name: Publish binaries
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: sudo apt-get install -y libquickfix-dev clang libboost-all-dev
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@klarpay'
      - run: npm install --build-from-source
        env:
          CXX: clang++
      - run: npx node-pre-gyp package publish
  mac:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: brew install boost automake
      - run: curl https://github.com/quickfix/quickfix/archive/refs/tags/v1.15.1.tar.gz  -L | tar xz
      - run: cd quickfix-1.15.1 && ./bootstrap && ./configure --with-boost=$(brew --prefix boost)/include/ && make CXXFLAGS="-DENABLE_BOOST_ATOMIC_COUNT=1 -I$(brew --prefix boost)/include/" && sudo make install
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@klarpay'
      - run: npm install --build-from-source
      - run: npx node-pre-gyp package publish
      # - run: npm ci
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}